### ISSUE TITLE
nflgame with Python 2.6

### ISSUE THREAD

**Issue by anontemp123** [BurntSushi/nflgame#89]
According to https://github.com/BurntSushi/nflgame :

"nflgame does not yet work on Python 3, but it should work with Python 2.6 and 2.7."

I get this error when importing:
  File "/usr/local/lib/python2.6/dist-packages/nflgame/sched.py", line 34, in _create_schedule
    if (datetime.datetime.utcnow() - last_updated).total_seconds() >= day:
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

Anyway to work around this without installing 2.7?  I might not be able to upgrade on one of the machines I use.

Also, is there a proper way to remove nflgame?  The pip command installed four packages for me.  I'm unsure if I have to uninstall in a specific order or anything like that.

Installing collected packages: beautifulsoup4, nflgame, ordereddict, pytz
  Running setup.py install for beautifulsoup4
  Running setup.py install for nflgame
    changing mode of build/scripts-2.6/nflgame-update-players from 644 to 755
    changing mode of /usr/local/bin/nflgame-update-players to 755
  Running setup.py install for ordereddict
  Running setup.py install for pytz
Successfully installed beautifulsoup4 nflgame ordereddict pytz

**Comment by hugovk** [comment]
It's probably about time to drop support for Python 2.6 at this point:

* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

Here's the pip installs for nflgame from PyPI for the last year:
```
$ pypinfo -d 365 --percent --pip nflgame pyversion
python_version percent download_count
-------------- ------- --------------
2.7              76.1%          3,144
3.5               9.4%            390
3.6               8.5%            352
3.4               5.3%            220
2.6               0.5%             22
3.7               0.1%              3
None              0.0%              1
```

**Comment by BurntSushi** [comment]
@hugovk You don't need to make the case. The only thing blocking progress on this is the will to do it.
